package com.mshell.notepad.core.db;

import android.annotation.SuppressLint;
import android.os.Parcel;
import android.os.Parcelable;

import androidx.annotation.NonNull;

import org.greenrobot.greendao.annotation.*;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Formatter;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "NOTE".
 */
@Entity
public class Note implements Parcelable {

    @Id(autoincrement = true)
    private Long id;
    private int note_id;
    private String title;
    private String description;
    private java.util.Date date_created;
    private java.util.Date last_updated;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Note() {
    }

    public Note(Long id) {
        this.id = id;
    }

    @Generated
    public Note(Long id, int note_id, String title, String description, java.util.Date date_created, java.util.Date last_updated) {
        this.id = id;
        this.note_id = note_id;
        this.title = title;
        this.description = description;
        this.date_created = date_created;
        this.last_updated = last_updated;
    }

    protected Note(Parcel in) {
        if (in.readByte() == 0) {
            id = null;
        } else {
            id = in.readLong();
        }
        note_id = in.readInt();
        title = in.readString();//"isi test"
        description = in.readString();
        last_updated = new Date(in.readLong());
    }

    public static final Creator<Note> CREATOR = new Creator<Note>() {
        @Override
        public Note createFromParcel(Parcel in) {
            return new Note(in);
        }

        @Override
        public Note[] newArray(int size) {
            return new Note[size];
        }
    };

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getNote_id() {
        return note_id;
    }

    public void setNote_id(int note_id) {
        this.note_id = note_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public java.util.Date getDate_created() {
        return date_created;
    }

    public void setDate_created(java.util.Date date_created) {
        this.date_created = date_created;
    }

    public java.util.Date getLast_updated() {
        return last_updated;
    }

    public void setLast_updated(java.util.Date last_updated) {
        this.last_updated = last_updated;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(@NonNull Parcel parcel, int i) {
        if (id == null) {
            parcel.writeByte((byte) 0);
        } else {
            parcel.writeByte((byte) 1);
            parcel.writeLong(id);
        }
        parcel.writeInt(note_id);
        parcel.writeString(title);
        parcel.writeString(description);
        parcel.writeLong(last_updated.getTime());
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
